### ISSUE TITLE
F and G indexing

### ISSUE THREAD

**Issue by EvaBr** [EvaBr/CFD-Lab#1]
In the instructions for setting F's and G's values only the values for indeces {0:imax}x{1:jmax} (for F) and {1:imax}x{0:jmax} (for G) are given. 
What are we supposed to set F(i, 0) and G(0, j) to? 
Anyone has any idea? Are those values even needed?

**Comment by ni-wei** [comment]
Is it right that based on Equations (10) and (11), indices {1:(imax-1)}x{1:jmax} are given for F and {1:imax}x{1:(jmax-1)} for G? However, based on Equations (12), do we need indices {0:imax}x{1:jmax} are given for F and {1:imax}x{0:jmax} for G?

**Comment by EvaBr** [comment]
Yes, from eq. (10) and (11) we only get values for indices {1:(imax-1)}x{1:jmax} in F matrix and {1:imax}x{1:(jmax-1)} in G matrix, but then we also have boundary values for F and G prescribed (see eq.18). So taking all this together, we have, as mentioned before, only values for  {0:imax}x{1:jmax} (for F) and {1:imax}x{0:jmax} (for G). But there are still no prescribed values for F(i,0) and G(0,j)...
I dont know what I am supposed to set them to. Should I just leave them alone?

**Comment by ni-wei** [comment]
I see. Sorry I did not read Equation (18).
I have no idea. Let's leave it alone for today :)
