### ISSUE TITLE
Boundary conditions

### ISSUE THREAD

**Issue by EvaBr** [EvaBr/CFD-Lab#2]
According to the 'Problems' section of the worksheet, the boundary condition on the upper wall should be a moving wall. So the fourth bound. cond. should be changed (it is currently set to be a no slip condition also).

+Just a thought -> what is in this cae the 'upper' boundary? It should be at the jmax, but the indexing of the arrays is exactly vice-versa .... we might need to think about this (and make some changes) at the end, if the results wont look like they should...

**Comment by EvaBr** [comment]
Ok I've had too much time today I guess :stuck_out_tongue_winking_eye: , and I've already repaired this; so that now the upper wall is moving with U_wall=1. I also fixed some typos, so that the code now compiles. :grinning:  
Please, feel free to check my code in return. :+1:

**Comment by ZhibinCH** [comment]
Ok, I will check it! thanks Eva

**Comment by EvaBr** [comment]
Thanks and no problem :yum:  
But, as mentioned before, we might need to change it later, after running the first simulations; for now I just set the 'upper' moving wall as the one at j=jmax.
