### ISSUE TITLE
10. Problems -> Ex. 6

### ISSUE THREAD

**Issue by ni-wei** [EvaBr/CFD-Lab#4]
Shall we discuss on Ex. 6 of Section 10 "Problems" sometime before our submission deadline? Below are my results and I list the important parameters:
# dt = 0.0095 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = -0.040150.
imax = 32, U[imax/2][7*jmax/2] = -0.159831.
imax = 64, U[imax/2][7*jmax/2] = -Nan.
# dt = 0.005 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = -0.040150.
imax = 32, U[imax/2][7*jmax/2] = -0.159831.
imax = 64, U[imax/2][7*jmax/2] = -0.213420.
imax = 128, U[imax/2][7*jmax/2] = -Nan.
# dt = 0.001 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = NA
imax = 32, U[imax/2][7*jmax/2] = NA
imax = 64, U[imax/2][7*jmax/2] = NA
imax = 128, U[imax/2][7*jmax/2] = -0.220711.

I have not tried imax =256. Also I compare the cases for imax = 16 & 32 between dt = 0.0095 and dt = 0.005, and cannot see any difference. That is why I did not recalculate the result for imax = 16 & 32 & 64 using dt = 0.001.

I also keep the result vtk files using Eva's latest main.c, and have some velocity screenshots.

**Comment by EvaBr** [comment]
Hey, I dont completely get what ex. 10.6. even wants from us. :/ I mean, based on your results, when would you say that U tends to infinity? :S Its so weird.... I dont get it. 

And btw, if you two agree, I shall clean the main function (comment the picture output etc.) and submit the finished version.

**Comment by ni-wei** [comment]
I agree. Thank you so much!
For Ex. 10.6, is it about the relation between maximal time step size and spatial step size to achieve stable discretization? Think in Scientific Computing 1 for heat equation with Dirichlet B.C., we have delta_t < (h^2)/4. Here it is not the same relation, however.

**Comment by EvaBr** [comment]
Yes but, where the step size is too big, we should see some problems (as U going to infinity). But I cant really see that in our results :S it seems that troubles begin when h is to big, and not too small as one might expect :persevere:

**Comment by ni-wei** [comment]
As per discussed just now, the results when dt = 0.001 should be as follows:

imax = 16, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 32, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 64, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 128, U[imax/2][7*jmax/2] = -0.220711.

**Comment by ni-wei** [comment]
After correcting the index error, the results are:

# dt = 0.0095 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = 0.198288.
imax = 32, U[imax/2][7*jmax/2] = 0.253764.
imax = 64, U[imax/2][7*jmax/2] = -Nan.

# dt = 0.005 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = 0.198288.
imax = 32, U[imax/2][7*jmax/2] = 0.253764.
imax = 64, U[imax/2][7*jmax/2] = 0.282674.
imax = 128, U[imax/2][7*jmax/2] = -Nan.

# dt = 0.001 (fixed, not adaptive), t_end = 100, omg = 1.7, itermax = 100

imax = 16, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 32, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 64, U[imax/2][7*jmax/2] = ... (not calculated, should be same with the previous 2 cases)
imax = 128, U[imax/2][7*jmax/2] = 0.296728.

**Comment by EvaBr** [comment]
Mission accomplished, closing the issue.
